### ISSUE TITLE
Design Spike: Strategy For Complete OSCAL Package Validation

### ISSUE THREAD

**Issue by ohsh6o** [18F/fedramp-automation#151]
**Extended Description**

As an SSP submitter and a FedRAMP reviewer, in order to see validations across a whole FedRAMP package, I would like to be able to upload one file, or multiple XML files to see results of analysis for an SSP, SAP, SAR, or POA&M in OSCAL format.

**Preconditions**

**Acceptance Criteria**
- [ ] ~A documented way of writing cross-document OSCAL FedRAMP Schematron rules~ see #258 
- [ ] ~A documented way of processing one or more OSCAL FedRAMP files in tandem~ see #258 
- [x] User Story(s) written in the backlog see #258 

**Story Tasks**
- [x] hash out in a working session

**Definition of Done**
 - [x] Acceptance criteria met - Each user story should meet the acceptance criteria in the description
 - [x] Documentation generated - update readme or contributing markdown as necessary.
 - [x] Architectural Decision Record completed as necessary for significant design choices

**Comment by danielnaab** [comment]
Proposed ADR in PR #252 and, to resolve remaining issues, created story #258 as a vertical slice through the system.
