### ISSUE TITLE
JAB Checklist

### ISSUE THREAD

**Issue by ohsh6o** [18F/fedramp-automation#292]
**Extended Description**
As a FedRAMP reviewer, to ensure I can see validation pre-checks organized accordingly to my role in the FART and the JAB, I would like to see validation messages and assertion views to be organized by either FART or JAB checklist styles.

**Preconditions**
- [ ] Spike analysis of JAB checklists and methodologies and how they potentially differ from the FART.

**Stories**
- [ ] Design FedRAMP JAB checklist metadata into validation rules
- [ ] Update existing rules
- [ ] Existing Schematron rules and style guide
- [ ] Add new assertion view to user interface
