### ISSUE TITLE
Integrate Validations into FedRAMP Review Workflows

### ISSUE THREAD

**Issue by ohsh6o** [18F/fedramp-automation#54]
As a FedRAMP PMO member, to ensure we can leverage our validations internally, I want the validations to be integrated into the FedRAMP workflow application.

**Extended Description**
The FedRAMP PMO has another project team that is developing a workflow management application for FedRAMP packages. At the conclusion of the 10x P2 Discovery Phase, we met with them and they began integration of the FedRAMP Validations with this workflow management application for review of SSPs to start. We will want to touch base with them, determine if there integration pattern is or will be possible without any significant design accommodations, and work out integration/smoke testing of some kind.

**Preconditions**

**Acceptance Criteria:**

- [ ] Documentation about the recommended approach to integrate with the FedRAMP Workflow
- [ ] An implementation plan to integrate with the FedRAMP flow
- [ ] A completed prototype integration reviewed and approved by the FedRAMP PMO and Agency Review Team

**Story Tasks**
- [ ] Tasks...

**Definition of Done**
 - [ ] Acceptance criteria met - Each user story should meet the acceptance criteria in the description
 - [ ] Unit test coverage of our code > 90%  (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*) this may be fuzzy and hard to prove
 - [ ] Code quality checks passed - Enable html tidy with XML code standards as part of the build (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*)
 - [ ] Accessibility: (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*) as we create guidance or documentation and reports (semantic tagging including aria tags): demonstrate with 0 errors reported for WCAG 2.1 AA standards using an automated scanner and 0 errors reported in manual testing
 - [ ] Code reviewed - Code reviewed by at least one other team members (or developed by a pair)
 - [ ] Source code merged - Code that’s demoed must be in source control and merged
 - [ ] Code must successfully build and deploy into staging environment (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*): this may evolve from xslt sh pipline into something more
 - [ ] Security reviewed and reported - Conduct vulnerability and compliance scanning. threat modeling? 
 - [ ] Code submitted must be free of medium- and high-level static and dynamic security vulnerabilities (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*)
 - [ ] Usability tests passed - Each user story should be easy to use by target users (development community? FedRAMP FART team)
 - [ ] Usability testing and other user research methods must be conducted at regular intervals throughout the development process (not just at the beginning or end). (*from [QASP](https://github.com/flexion/TTS-10x/wiki/TTS-QASP)*)
 - [ ] Code refactored for clarity - Code must be clean, self-documenting
 - [ ] No local design debt
 - [ ] Load/performance tests passed - test data needed - saxon instrumentation
 - [ ] Documentation generated - update readme or contributing markdown as necessary.
 - [ ] Architectural Decision Record completed as necessary for significant design choices
