### ISSUE TITLE
As a FedRAMP PMO member, to be ensure the as much validation can be automated, I want any OSCAL SSP validation that can be automated to be automated.

### ISSUE THREAD

**Issue by ohsh6o** [18F/fedramp-automation#58]
**Context:**

As part of the 10x Phase Two Discovery work, the 10x team worked with the FedRAMP PMO to understand and prototype against a categorized list of checks that FedRAMP reviewers perform without any automated checking. FedRAMP staff determined how many of those were, as part of this work when initiated in the Phase Two Discovery Phase, easily automated and conducive for automated validation. We call these "the 60%" (because 60% are estimated to fall into this category).

[This list is maintained in a spreadsheet](https://docs.google.com/spreadsheets/d/1l3MlnJ2CS9awsTavVM9YmjLEzzHb5ul-lArzlOOL7uI/edit#gid=1453941420). This list is a representation of individual checks a reviewer does in their head as they fill out the more high-level JAB or [agency review checklist like this one](https://docs.google.com/spreadsheets/d/1Rcw7KvUudIPMSMmo0lbhXE3QgqqaS76S0BmFC8ThrXA/edit#gid=177951143).

We will want to track how we handle this across the P3 and potential P4 of the project, as this is part of the core requirements for this project, it can reasonably broken down into different validations or groups of validations to track progress.

**Acceptance Criteria:**
- [ ] Individual validations are catalogued
- [ ] Individual validations are mapped into [the high-level checklist "Section C" checks](https://github.com/18F/fedramp-automation/tree/master/resources/validations#section-c-overall-ssp-checks)
- [ ] Error messaging is consistent, vetted, and endorsed by the FedRAMP PMO and reviewers
- [ ] Example of positive tests (no invalid items return from the validations) and negative (invalid items are found and are correctly returned as errors or warnings) tests

**Comment by ohsh6o** [comment]
Deprecating for conversion into epic/goal theme label.

https://github.com/orgs/18F/projects/22?card_filter_query=label%3A%22g%3A+tool+integration%22
