### ISSUE TITLE
MVP User Interface for Presenting Validation Results 

### ISSUE THREAD

**Issue by ohsh6o** [18F/fedramp-automation#82]
**Context:**

Currently, the reviewers use [this reporting form](https://docs.google.com/spreadsheets/d/1Rcw7KvUudIPMSMmo0lbhXE3QgqqaS76S0BmFC8ThrXA/edit#gid=177951143) when reviewing a SSP. A user interface could use this as inspiration build a contextually relevant report and framing OSCAL validation errors in a context as if (and not identically so) to how they would flag errors or inconsistencies in a FedRAMP Word template SSP.

Currently, we use [an open-source XSLT stylesheet to convert the SVRL to very basic HTML output](https://github.com/18F/fedramp-automation/blob/f0ff6e5581a1c137cd18a244806150b3f0410d87/resources/validations/lib/svrl2html.xsl) (and not contextually linked to the SSP validated, only by means of the references in SVRL assertions and their `location` attribute).

**Acceptance Criteria:**
- [x] An ADR explaining the architecture and 
- [x] An interface that presents information about validation errors in a language and method that the reviewer understands
- [x] Documentation on how to use it (if and when hosted)

**Dependencies:**
- More representative SSP data to thoroughly exercise the validations and present errors in the UI
- Hosting environment (potentially later)

**Tasks**
 - Investigate Federalist access for deployment #84

**Comment by ohsh6o** [comment]
@wendellpiez provided a link to a branch in a fork of the fedramp-automation with code Brian Ruf had asked him [to prototype SSP representation](https://github.com/GSA/fedramp-automation/compare/master...wendellpiez:oscal-presentation). We can discuss if this is useful and/or there is more interest.
